name: nestify
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  # Redux
  redux: ^5.0.0
  flutter_redux: ^0.10.0
  redux_epics: ^0.15.1

  # DI
  get_it: ^7.2.0

  # Freezed
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0

  # Navigation
  go_router: ^6.2.0

  # Firebase
  firebase_core: ^2.7.1
  firebase_auth: ^4.2.10
  cloud_firestore: ^4.4.4
  firebase_storage: ^11.0.15
  google_sign_in: ^6.0.2
  firebase_dynamic_links: ^5.1.1

  # General
  flutter_svg: ^2.0.3
  image_picker: ^0.8.7
  url_launcher: ^6.1.10
  cached_network_image: ^3.2.3
  qr_flutter: ^4.0.0
  share_plus: ^4.5.3
  screenshot: ^1.3.0
  uuid: ^3.0.7

dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0

  flutter_lints: ^2.0.0

  build_runner: ^2.3.3

  # Freezed
  freezed: ^2.3.2
  json_serializable: ^6.6.1

  # Asset path generator
  flutter_gen_runner: ^5.2.0

flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/images/login/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
