# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  lane :release do
    previous_build_number = google_play_track_version_codes(
      package_name: 'com.gmail.ivan.morozyk.nestify',
      track: "internal",
    )[0]

    current_build_number = previous_build_number + 1

    increment_version_code(
      gradle_file_path: "./app/build.gradle",
      version_code: current_build_number
    )

    gradle(
      flavor: "prod",
      task: "bundle",
      flags: "-Ptarget=lib/main_prod.dart"
    )

    upload_to_play_store(
      package_name: "com.gmail.ivan.morozyk.nestify",
      aab: "../build/app/outputs/bundle/prodRelease/app-prod-release.aab",
      track: 'internal',
      release_status: 'draft'
    )
  end
end
