name: run-tests-before-enable-merge
run-name: ${{ github.actor }} wants to merge a pull request
on:
  pull_request:
    types: [ opened, reopened ]
jobs:
     run-tests:
        runs-on: macos-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v2

          - name: Authenticate with GitHub API
            uses: octokit/request-action@v2.x
            with:
              route: GET /app
            env:
              GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

          - uses: octokit/request-action@v2.x
            id: create_check_run
            with:
              route: POST /repos/{owner}/{repo}/check-runs
              owner: Sanusy
              repo: nestify
              name: "Test check run"
              conclusion: "in_progress"
              head_sha: ${{ github.sha }}
            env:
              GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

          - name: Install Flutter
            uses: subosito/flutter-action@v2
            with:
              flutter-version: '3.7.7'
              channel: 'stable'

          - name: Flutter get
            working-directory: ${{ github.workspace }}
            run: flutter pub get

          - name: Flutter run build runner
            working-directory: ${{ github.workspace }}
            run: flutter pub run build_runner build --delete-conflicting-outputs

          - name: Flutter run tests
            working-directory: ${{ github.workspace }}
            run: flutter test

          - uses: octokit/request-action@v2.x
            id: update_check_run
            with:
              route: PATCH /repos/{owner}/{repo}/check-runs/{check_run_id}
              owner: Sanusy
              repo: nestify
              check_run_id: ${{ fromJson(steps.create_check_run.outputs.data).id }}
              conclusion: "success"
            env:
              GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

