name: run-tests-before-enable-merge
run-name: ${{ github.actor }} wants to merge a pull request
on:
  pull_request:
    types: [ opened, reopened ]
jobs:
     run-tests:
        runs-on: macos-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v2

          - name: Create check run
            id: create_check_run
            run: |
              response=$(curl -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}"\
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/Sanusy/nestify/check-runs \
                -d '{"name":"Run unit tests before enable merge","status":"in_progress"}')
              echo "::set-output name=response::${response}"

          - name: Install Flutter
            uses: subosito/flutter-action@v2
            with:
              flutter-version: '3.7.7'
              channel: 'stable'

          - name: Print response
            run: |
              echo "${{ steps.create_check_run.outputs.response }}"

          - name: Flutter get
            working-directory: ${{ github.workspace }}
            run: flutter pub get

          - name: Flutter run build runner
            working-directory: ${{ github.workspace }}
            run: flutter pub run build_runner build --delete-conflicting-outputs

          - name: Flutter run tests
            working-directory: ${{ github.workspace }}
            run: flutter test

          - name: Create check run
            run: |
              curl -L \
              -X PATCH \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}"\
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/Sanusy/nestify/check-runs/${{ fromJson(steps.create_check_run.outputs.response).id }} \
              -d '{"name":"Run unit tests before enable merge","status":"completed"}'

